version: "3.0"
networks:
  backend:
  frontend:
services:



  app:
    build: ./                     # Build Dockerfile in current directory
    environment:
      MONGO_USER: root
      MONGO_PASSWORD: example
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB_NAME: hello_world
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks: 
      - frontend
      - backend

  mongodb:
    image: mongo
    volumes:
      - $PWD/mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - backend

  nginx:
    image: ployst/nginx-ssl-proxy # use image from hub.docker.com
    environment:
      ENABLE_SSL: "true"
      TARGET_SERVICE: app:4300 #my docker env
      SERVER_NAME: localhost
    volumes:
      - ./certs/lh.crt:/etc/secrets/proxycert
      - ./certs/lh.key:/etc/secrets/proxykey
      - ./certs/dhparam.pem:/etc/secrets/dhparam
    ports:
      - 443:443
    networks:
      - frontend
