version: "3.0"
networks:
  backend:
  frontend:
services:
  app:
    build: ./                     # Build Dockerfile in current directory
    env_file: ".env"
    networks:
      - frontend
      - backend
  mongodb:
    image: mongo
    env_file: ".env"
    volumes:
      - $PWD/mongo_data:/data/db
    networks:
      - backend
  nginx:
    image: ployst/nginx-ssl-proxy # use image from hub.docker.com
    environment:
      ENABLE_SSL: "true"
      TARGET_SERVICE: app:4300 #my docker env
      SERVER_NAME: localhost
    volumes:
      - ./certs/lh.crt:/etc/secrets/proxycert
      - ./certs/lh.key:/etc/secrets/proxykey
      - ./certs/dhparam.pem:/etc/secrets/dhparam
    ports:
      - 443:443
    networks:
      - frontend
